wallpaper {
    monitor = DP-1
    path = ~/Pictures/Images & Videos/BG/THE.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/Pictures/Images & Videos/BG/TH6.png
    fit_mode = cover
}